### ISSUE TITLE
deposit_collateral exception

### ISSUE THREAD

**Issue by seaify** [scallop-io/sui-scallop-sdk#19]
```
const { ScallopClient, ScallopAddress } = require('@scallop-io/sui-scallop-sdk');
require('dotenv').config({ path: '.env' });

const NETWORK = 'mainnet';

async function test() {

    const scallopAddress = new ScallopAddress({
        id: '649bdadbb946e3b1853f3d4d', // test addresses of new contract
        network: NETWORK,
    });
    await scallopAddress.read();
    const client = new ScallopClient(
        {
            secretKey: process.env.SUI_PRIVATE_KEY,
            networkType: NETWORK,
        },
        scallopAddress
    );

    const marketData = await client.queryMarket();
    console.info('marketData:', marketData);

    const openObligationResult = await client.openObligation();
    console.info('openObligationResult:', openObligationResult);

    const obligations = await client.getObligations();
    const depositCollateralResult = await client.depositCollateral(
        'sui',
        10 ** 1,
        true,
        obligations[0]?.id
    );
    console.info('depositCollateralResult:', depositCollateralResult);
    console.log(depositCollateralResult.effects.status.status)
}

test()

```

get this error  `error: 'MoveAbort(MoveLocation { module: ModuleId { address: 3027af7d3bde467b61f5f1141c830fe191b22febc38f32405b601b41b5a8959b, name: Identifier("deposit_collateral") }, function: 0, instruction: 18, function_name: Some("deposit_collateral") }, 257) in command 1'`

what does this mean ?

**Comment by mr-donor** [comment]
Thanks for your feedback, this error is caused by a whitelist problem on the contract side, you using the wrong addresses id (wrong contract) to interact, changing the id to `ADDRESSES_ID` from `const { ScallopClient, ScallopAddress, ADDRESSES_ID } = require('@scallop-io/sui-scallop-sdk');` is what you want.

Anyway, we'll sort out the list of error codes in our document later let Devs easy to debug it.
